name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r infra/requirements.txt
          pip install pytest pytest-cov bandit safety
      
      - name: Code quality checks
        run: make quality
      
      - name: Run tests with coverage
        run: make test-coverage
      
      - name: Security scan
        run: make security-scan
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./htmlcov/coverage.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy to AWS
        run: make deploy
      
      - name: Health check
        run: make health-check