name: CI/CD Pipeline

on:
  push:
    branches: [ main, rebuild/v3-clean ]
  pull_request:
    branches: [ main, rebuild/v3-clean ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r infra/requirements.txt
        pip install pytest ruff mypy bandit pytest-cov safety
    
    - name: Run code quality checks
      run: |
        cd infra
        ruff check . --fix || echo "Ruff check completed"
        ruff format . || echo "Ruff format completed"
        mypy src/ || echo "MyPy warnings found"
    
    - name: CDK Security Check
      run: |
        cd infra
        npm install -g aws-cdk
        cdk diff --strict > cdk.diff || true
        if grep -q "+ AWS::IAM::Policy\|+ AWS::IAM::Role\|+ IAM::Policy\|+ IAM::Role" cdk.diff; then
          echo "❌ IAM privilege escalation detected in CDK diff"
          echo "Detected changes:"
          grep "+ AWS::IAM\|+ IAM::" cdk.diff || true
          exit 1
        fi
        echo "✅ No IAM privilege escalation detected"
    
    - name: Run security analysis
      run: |
        cd infra
        bandit -r src/ -ll || echo "Security warnings found"
        safety check || echo "Dependency vulnerabilities found"
    
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=infra/src --cov-report=term-missing --cov-report=xml --cov-fail-under=5
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./infra/coverage.xml
        flags: backend
        name: backend-coverage
      continue-on-error: true

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Run lint
      run: npm run lint || echo "Lint completed"
    
    - name: Run type check
      run: npm run type-check || echo "Type check completed"
    
    - name: Run tests with coverage
      run: |
        npm run test:coverage --coverageThreshold='{"global":{"branches":80,"functions":80,"lines":80,"statements":80}}'
    
    - name: Build application
      run: npm run build || echo "Build completed"

  e2e-test:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    
    - name: Install Playwright
      run: |
        cd frontend
        npm install --legacy-peer-deps
        npx playwright install --with-deps
    
    - name: Run E2E tests
      run: |
        cd frontend
        npm run test:e2e || echo "E2E tests completed"
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true